dataset:
  name: FB15k-237
  path: ./dataset/fb15k237


model:
  encoder:
    type: RGCN
    hidden_layer_size: 200
    embedding_dim: 200
    num_layers: 2
    dropout: 0.2
    num_bases : 30
  decoder:
    type: DistMult
    w_init: xavier_uniform
    w_gain: true
    b_init: true
  
training:
  epochs: 100
  batch_size: 1024
  learning_rate: 0.01
  weight_decay: 0.0001
  negative_sampling_ratio: 10
  evaluation_frequency: 10
  save_frequency: 20