dataset:
  name: WN18RR
  path: ./dataset/wn18rr

model:
  encoder:
    type: RGCN
    hidden_layer_size: 200
    embedding_dim: 200
    num_layers: 2
    dropout: 0.2
    num_bases : 11
  decoder:
    type: DistMult
    w_init: xavier_uniform
    w_gain: false
    b_init: false
  
training:
  epochs: 200
  sampling:
    batch_size: 2048
    negative_sampling_ratio: 3
    head_corrupt_prob: 0.5
  optimiser:
    learning_rate: 0.001
    weight_decay: 0.0001
  evaluation_frequency: 1
  save_frequency: 100
  evaluation:
    batch_size: 64
    verbose: true
    filter_candidates: true
    mrr_top_k: 10
    hits_at_k: [1, 3, 10]