dataset:
  name: WN18RR
  path: ./dataset/wn18rr

model:
  encoder:
    type: RGCN
    hidden_layer_size: 100
    embedding_dim: 200
    num_layers: 2
    dropout: 0.2
    num_bases : 11
  decoder:
    type: DistMult
    l2_penalty_type: schlichtkrull-l2
    l2_penalty : 0.01
    w_gain: false
    b_init: false
  
training:
  epochs: 50
  sampling:
    batch_size: 2048
    method: sample
    negative_sampling_ratio: 5
    head_corrupt_prob: 0.5
  optimiser:
    learning_rate: 0.001
    weight_decay: 0.0001
  evaluation_frequency: 1
  save_frequency: 50
  evaluation:
    verbose: true
    filter_candidates: true
    hits_at_k: [1, 3, 10]